CREATE TABLE IF NOT EXISTS live_user_predictions_ro16 (
    id SMALLINT(6) NOT NULL,
    username CHAR(50) UNIQUE NOT NULL,
    firstname CHAR(50) NOT NULL,
    surname CHAR(50) NOT NULL,
    score145_p TINYINT(4) NOT NULL,
    score146_p TINYINT(4) NOT NULL,
    score147_p TINYINT(4) NOT NULL,
    score148_p TINYINT(4) NOT NULL,
    score149_p TINYINT(4) NOT NULL,
    score150_p TINYINT(4) NOT NULL,
    score151_p TINYINT(4) NOT NULL,
    score152_p TINYINT(4) NOT NULL,
    score153_p TINYINT(4) NOT NULL,
    score154_p TINYINT(4) NOT NULL,
    score155_p TINYINT(4) NOT NULL,
    score156_p TINYINT(4) NOT NULL,
    score157_p TINYINT(4) NOT NULL,
    score158_p TINYINT(4) NOT NULL,
    score159_p TINYINT(4) NOT NULL,
    score160_p TINYINT(4) NOT NULL,
    score161_p TINYINT(4) NOT NULL,
    score162_p TINYINT(4) NOT NULL,
    score163_p TINYINT(4) NOT NULL,
    score164_p TINYINT(4) NOT NULL,
    score165_p TINYINT(4) NOT NULL,
    score166_p TINYINT(4) NOT NULL,
    score167_p TINYINT(4) NOT NULL,
    score168_p TINYINT(4) NOT NULL,
    score169_p TINYINT(4) NOT NULL,
    score170_p TINYINT(4) NOT NULL,
    score171_p TINYINT(4) NOT NULL,
    score172_p TINYINT(4) NOT NULL,
    score173_p TINYINT(4) NOT NULL,
    score174_p TINYINT(4) NOT NULL,
    score175_p TINYINT(4) NOT NULL,
    score176_p TINYINT(4) NOT NULL,
    lastupdate TIMESTAMP NULL,
    points_total SMALLINT(6) DEFAULT '0'
);
