CREATE TABLE IF NOT EXISTS live_user_predictions_qf (
    id SMALLINT(6) NOT NULL,
    username CHAR(50) UNIQUE NOT NULL,
    firstname CHAR(50) NOT NULL,
    surname CHAR(50) NOT NULL,
    score177_p TINYINT(4) NOT NULL,
    score178_p TINYINT(4) NOT NULL,
    score179_p TINYINT(4) NOT NULL,
    score180_p TINYINT(4) NOT NULL,
    score181_p TINYINT(4) NOT NULL,
    score182_p TINYINT(4) NOT NULL,
    score183_p TINYINT(4) NOT NULL,
    score184_p TINYINT(4) NOT NULL,
    score185_p TINYINT(4) NOT NULL,
    score186_p TINYINT(4) NOT NULL,
    score187_p TINYINT(4) NOT NULL,
    score188_p TINYINT(4) NOT NULL,
    score189_p TINYINT(4) NOT NULL,
    score190_p TINYINT(4) NOT NULL,
    score191_p TINYINT(4) NOT NULL,
    score192_p TINYINT(4) NOT NULL,
    lastupdate TIMESTAMP NULL,
    points_total SMALLINT(6) DEFAULT '0'
);
